
function Hd = lowpassF
%LPFLTR Returns a discrete-time filter object.
 
% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 10-Dec-2018 15:18:09
 
% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.
 
% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency
 
N  = 4;     % Order
Fc = 5500;  % Cutoff Frequency
 
% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
 
% [EOF]
